workflows:
  flutter-build:
    name: Flutter Build
    environment:
      vars:
        API_URL: "https://workspaceapi-server-production-4343.up.railway.app/"
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd flutter_app
          flutter pub get
      
      - name: Build Android APK
        script: |
          cd flutter_app
          flutter build apk --release --dart-define=API_URL=$API_URL
    artifacts:
      - flutter_app/build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - checho.mlj@gmail.com